query GetAdjacentPosts($createdAt: DateTime!, $slug: String!) {
  next: posts(
    first: 1
    orderBy: createdAt_ASC
    where: { slug_not: $slug, AND: { createdAt_gte: $createdAt } }
  ) {
    title
    featuredImage {
      url
    }
    createdAt
    slug
  }
  previous: posts(
    first: 1
    orderBy: createdAt_DESC
    where: { slug_not: $slug, AND: { createdAt_lte: $createdAt } }
  ) {
    title
    featuredImage {
      url
    }
    createdAt
    slug
  }
}
