query GetCategoryPost($slug: String!) {
  category(where: { slug: $slug }) {
    name
    slug
  }
  postsConnection(where: { categories_some: { slug: $slug } }) {
    edges {
      cursor
      node {
        author {
          bio
          name
          id
          photo {
            url
          }
        }
        createdAt
        slug
        title
        excerpt
        featuredImage {
          url
        }
        categories {
          name
          slug
        }
      }
    }
  }
}
