query GetPostDetails($slug: String!, $locales: [Locale!]!) {
  post(where: { slug: $slug }, locales: $locales) {
    title
    excerpt
    featuredImage {
      url
    }
    author {
      name
      bio
      photo {
        url
      }
    }
    createdAt
    updatedAt
    slug
    content {
      raw
    }
    categories {
      name
      slug
    }
  }
}
