query GetPostsPerPage($first: Int, $skip: Int) {
  postsConnection(first: $first, skip: $skip, orderBy: createdAt_DESC) {
    edges {
      cursor
      node {
        author {
          bio
          name
          id
          photo {
            url
          }
        }
        createdAt
        slug
        title
        excerpt
        featuredImage {
          url
        }
        categories {
          name
          slug
        }
      }
    }
  }
}