query GetPostDetails($slug: String!) {
  post(where: { slug: $slug }) {
    title
    excerpt
    featuredImage {
      url
    }
    author {
      name
      bio
      photo {
        url
      }
    }
    createdAt
    slug
    content {
      raw
    }
    categories {
      name
      slug
    }
  }
}
