query GetSimilarPosts($slug: String!, $categories: [String!]) {
  posts(
    where: {
      slug_not: $slug
      AND: { categories_some: { slug_in: $categories } }
    }
    last: 3
  ) {
    title
    featuredImage {
      url
    }
    createdAt
    slug
  }
}
